name: flutter_rpg_audiodrama
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  http: ^1.3.0
  shared_preferences: ^2.4.0
  provider: ^6.1.2
  go_router: ^14.7.2
  cloud_firestore: ^5.6.2
  uuid: ^4.5.1
  badges: ^3.1.2
  lottie: ^3.3.1
  intl: ^0.19.0
  flutter_expandable_fab: ^2.3.0
  fl_chart: ^0.70.2
  supabase_flutter: ^2.8.4
  flutter_dotenv: ^5.2.1
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  flutter_staggered_grid_view: ^0.7.0
  url_launcher: ^6.3.1
  file_picker: ^10.1.0
  string_similarity: ^2.1.1
  just_audio: ^0.9.46

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - dotenv
    - assets/sheets/
    - assets/images/
    - assets/lotties/
  fonts:
    - family: Bungee
      fonts:
        - asset: assets/fonts/bungee.ttf
    - family: SourceSerif4
      fonts:
        - asset: assets/fonts/source_serif4.ttf
        - asset: assets/fonts/source_serif4-italic.ttf
          style: italic
